### PR TITLE
Test comment with WPT link for big metrics

### LINKED ISSUE #146: Add WebPageTest link when too big
At the moment when the test results are too big for the comment we add this:

> Webpage test results that are too big for a comment are available as [the action's artifact](https://github.com/HTTPArchive/custom-metrics/actions/runs/10973750435/artifacts/1961803918).

Example:
https://github.com/HTTPArchive/custom-metrics/pull/145#issuecomment-2365230655

It would be nice if we also got a WebPageTest link so we can see them there too. Is this possible @max-ostapenko ?

### PR DESCRIPTION
**Pull request by max-ostapenko**
Resolves #146

- applied formatting (no other changes) to `css-variables.js` to trigger test results

---
**Test websites**:

- https://www.morgenpost.de/politik/article407241629/game-changer-fuer-die-ukraine-bahnt-sich-an-putin-droht.html

### CODE REVIEW

**Comment by tunetheweb** [comment]
Thanks for working on this so quickly! I wonder can we make them more similar.

In above example:
- The first one (almanac.httparchive.org) is in a summary/defaults, but the second is not. Can we put both in summary/default?
- The "Next WebPageTest results are too big for a comment" I presume is for the second test? But that's before that header.
- Bullet point instead of exapndable/collapsible arrow.

So I'm thinking something like this:

------




<details>
<summary><strong>Custom metrics for https://almanac.httparchive.org/en/2022/</strong></summary>

WPT test run results: http://webpagetest.httparchive.org/results.php?test=240921_5X_15

Changed custom metrics values:
```json
{
  "_css-variables": {
    "summary": {}
  }
}
```
</details>

<details>
<summary><strong>Custom metrics for https://www.morgenpost.de/politik/article407241629/game-changer-fuer-die-ukraine-bahnt-sich-an-putin-droht.html</strong></summary>

WPT test run results: http://webpagetest.httparchive.org/results.php?test=240921_AY_17

WebPageTest results are too big for a comment - [download them as an artifact](https://github.com/HTTPArchive/custom-metrics/actions/runs/10975750057/artifacts/1962161330).

</details>

**Comment by max-ostapenko** [comment]
The point is that there is only one artifact link no matter how many more pages were tested.
So putting it under each toggle separately will be confusing.

And since there is basically no unique content to put under the toggle, I got rid of them in favor of a bullet point.

And maybe we just use original WPT results instead of messing with artifact file.

Maybe this look is nicer?

---




-  https://almanac.httparchive.org/en/2022/

   [WPT test results](http://webpagetest.httparchive.org/results.php?test=240921_5X_15), [JSON](https://webpagetest.httparchive.org/jsonResult.php?test=240921_5X_15&pretty=1)

  <details><summary>Changed custom metrics values:</summary>

  ```json
  {
    "_css-variables": {
      "summary": {}
    }
  }
  ```
</details>
      
- https://www.morgenpost.de/politik/article407241629/game-changer-fuer-die-ukraine-bahnt-sich-an-putin-droht.html

  [WPT test results](http://webpagetest.httparchive.org/results.php?test=240921_AY_17), [JSON](https://webpagetest.httparchive.org/jsonResult.php?test=240921_AY_17&pretty=1)

- https://www.example.com

  [WPT test results](http://webpagetest.httparchive.org/results.php?test=240921_AY_17), [JSON](https://webpagetest.httparchive.org/jsonResult.php?test=240921_AY_17&pretty=1)

**Comment by tunetheweb** [comment]
> The point is that there is only one artifact link no matter how many more pages were tested. So putting it under each toggle separately will be confusing.

Ah gotcha. Didn’t that of that before.

it kinda looked odd in the changes you’ve made here so far. And inconsistent between the tests that had changes (WPT link in summary) and that didn’t (WPT link not in summary).

> And since there is basically no unique content to put under the toggle, I got rid of them in favor of a bullet point.

Well the WPT test link is the unique bit of content.

> And maybe we just use original WPT results instead of messing with artifact file.

Yeah to me link would be fine. And maybe instead of changed results it could be “Cannot display changed results due to GitHub comment limits. Use the link instead.” Or something like that.

> Maybe this look is nicer?

I think it’s still a bit confusing that the “Change custom metric” doesn’t seem to belong to the first bullet.

Honestly if just have them all under summary/details with the link, and the changed metric (or above message if can’t display those for that test).

**Comment by max-ostapenko** [comment]
Updated example above (toggles, JSON links, no artifacts).
WDYT?

**Comment by tunetheweb** [comment]
LGTM!

**Comment by max-ostapenko** [comment]
@tunetheweb please review

**Comment by max-ostapenko** [comment]
Interestingly add-pr-comment step removed the wrong comment:
> @[github-actions](https://github.com/apps/github-actions) github-actions bot deleted a comment from [tunetheweb](https://github.com/tunetheweb) [25 minutes ago](https://github.com/HTTPArchive/custom-metrics/pull/147#event-14635698018)

Let's see if it can be reproduced again.

**Comment by tunetheweb** [comment]
> [WPT test results](http://webpagetest.httparchive.org/results.php?test=241014_QN_5)
> 
> Cannot display changed custom metrics due to comment size limits, use [test JSON](https://webpagetest.httparchive.org/jsonResult.php?test=241014_QN_5&pretty=1) instead.

Been a while since I looked at this, so was confused initially. I wanted to be linked to this screen:
https://webpagetest.httparchive.org/result/241014_QN_5/1/details/#waterfall_view_step1

But neither of the above links does that directly (though fairly easy to get there from first link but I missed that as was distracted by the second link).

WDYT about changing this:

> Cannot display changed custom metrics due to comment size limits, use [test JSON](https://webpagetest.httparchive.org/jsonResult.php?test=241014_QN_5&pretty=1) instead.

To this:

> Cannot display changed custom metrics due to comment size limits, use [test details](https://webpagetest.httparchive.org/result/241014_QN_5/1/details/#waterfall_view_step1) or [test JSON](https://webpagetest.httparchive.org/jsonResult.php?test=241014_QN_5&pretty=1) instead.

**Comment by max-ostapenko** [comment]
A good idea about the details page!
But I would keep the other text as it is to avoid having a third and duplicated link.

**Comment by max-ostapenko** [comment]
`document.getElementById("waterfall_view_step1")` returns null, so I'll use the next best anchor: https://webpagetest.httparchive.org/result/241014_QN_5/1/details/#result

**Comment by max-ostapenko** [comment]
@tunetheweb with new link we save 2 clicks :)


At the same time I notice that I can get to [WPT results details](https://webpagetest.httparchive.org/result/241014_2M_7/1/details/#result) faster than to [JSON](https://webpagetest.httparchive.org/jsonResult.php?test=241014_2M_7&pretty=1)

@pmeenan So I thought maybe we could improve custom metrics rendering in WPT a bit to avoid needing JSON link (rendering huge JSONs).
Screenshot 2024-10-14 at 18 56 15

**Comment by tunetheweb** [comment]
Yeah the fact it's huge (and so I needed to search for the custom metrics) was the main reason I didn't like the JSON.

Can always get that JSON from the link if wanted:

image

**Review by tunetheweb — APPROVED** [review]

**Comment by pmeenan** [comment]
FWIW, the JSON API [takes query params](https://github.com/HTTPArchive/webpagetest/blob/master/www/jsonResult.php#L107) to strip out things and make it a lot smaller and faster.

`&requests=0&average=0&standard=0` should make it quite a bit smaller.

**Comment by max-ostapenko** [comment]
https://webpagetest.httparchive.org/jsonResult.php?test=241014_2M_7&pretty=1&requests=0&average=0&standard=0
I didn't notice any difference, still 40.8Mb

Seems these parameters require `&pretty=0`, which then makes it unreadable.

**Pull request merged**
