### PR TITLE
Update `fugu-apis.js`

### PR DESCRIPTION
**Pull request by tomayac**
I have a generator script over in the old legacy repo: https://github.com/HTTPArchive/legacy.httparchive.org/blob/master/bin/create-fugu.js. For now, I have just copied its output manually over here. Would it be fine for me to add the generator script to the present repo?

### CODE REVIEW

**Comment by rviscomi** [comment]
Yeah it'd be fine to migrate that script over here.

**Comment by tunetheweb** [comment]
> Would it be fine for me to add the generator script to the present repo?

Think so but not into the `dist` folder as that’s automatically copied to WPT agents and run. FYI @pmeenan

**Comment by tomayac** [comment]
Added the script. If more metrics need a generator script, we could generalize the `npm prepare` script. For now, it just executes my script.

**Review by rviscomi — APPROVED** [review]
Linter is complaining but otherwise LGTM

**Comment by tomayac** [comment]
Made the linter happy 😃.

**Pull request merged**
