### PR TITLE
Update Fugu API data

### PR DESCRIPTION
**Pull request by tomayac**
Improved the Pointer Lock detection.

### CODE REVIEW

**Comment by tunetheweb** [comment]
Looks like you've reordered this to be alphabetical, which makes it difficult to review.

Could you comment on what was actually changed? Looks like you added `HTMLParagraphElement` but not sure why?

Also, could we have a WebPageTest link to show it's all still working now?

**Comment by tomayac** [comment]
This is the actual change: https://github.com/tomayac/fugu-api-data/commit/c35a347176648ae445e284f518fce69bbbe4d51e. 

I ping you an off-thread link so you can see it in action.

**Review by tunetheweb — APPROVED** [review]
I ran the new code on https://whatwebcando.today/ in this test: https://www.webpagetest.org/result/221025_AiDc7D_D5Y/1/details/#waterfall_view_step1
Results LGTM

I also ran it on a site using Pointer Lock (not public yet) and confirmed that works too.

**Comment by tomayac** [comment]
For the sake of completeness, this is the result of the test from https://github.com/HTTPArchive/custom-metrics/pull/55#pullrequestreview-1154713866. 

```json
{
	"Absolute Orientation Sensor": ["https:\/\/whatwebcando.today\/client\/index.422cb780.js"],
	"Accelerometer": ["https:\/\/whatwebcando.today\/client\/index.422cb780.js"],
	"Ambient Light Sensor": ["https:\/\/whatwebcando.today\/client\/index.422cb780.js"],
	"Async Clipboard": ["https:\/\/whatwebcando.today\/client\/index.422cb780.js"],
	"Async Clipboard (Images)": ["https:\/\/whatwebcando.today\/client\/index.422cb780.js"],
	"Background Sync": ["https:\/\/whatwebcando.today\/client\/index.422cb780.js"],
	"Badging": ["https:\/\/whatwebcando.today\/client\/index.422cb780.js"],
	"Cache Storage": ["https:\/\/whatwebcando.today\/client\/index.422cb780.js", "https:\/\/storage.googleapis.com\/workbox-cdn\/releases\/4.3.1\/workbox-core.prod.js", "https:\/\/whatwebcando.today\/service-worker.js"],
	"Contact Picker": ["https:\/\/whatwebcando.today\/client\/index.422cb780.js"],
	"Content Index": ["https:\/\/whatwebcando.today\/client\/index.422cb780.js"],
	"Credential Management": ["https:\/\/whatwebcando.today\/client\/index.422cb780.js"],
	"Device Memory": ["https:\/\/whatwebcando.today\/client\/index.422cb780.js"],
	"EyeDropper": ["https:\/\/whatwebcando.today\/client\/index.422cb780.js"],
	"Gravity Sensor": ["https:\/\/whatwebcando.today\/client\/index.422cb780.js"],
	"Gyroscope": ["https:\/\/whatwebcando.today\/client\/index.422cb780.js"],
	"Idle Detection": ["https:\/\/whatwebcando.today\/client\/index.422cb780.js"],
	"Linear Acceleration Sensor": ["https:\/\/whatwebcando.today\/client\/index.422cb780.js"],
	"Magnetometer": ["https:\/\/whatwebcando.today\/client\/index.422cb780.js"],
	"Payment Request": ["https:\/\/whatwebcando.today\/client\/index.422cb780.js"],
	"Periodic Background Sync": ["https:\/\/whatwebcando.today\/client\/index.422cb780.js"],
	"Persistent Storage": ["https:\/\/whatwebcando.today\/client\/index.422cb780.js"],
	"Push": ["https:\/\/whatwebcando.today\/client\/index.422cb780.js"],
	"Relative Orientation Sensor": ["https:\/\/whatwebcando.today\/client\/index.422cb780.js"],
	"Screen Wake Lock": ["https:\/\/whatwebcando.today\/client\/index.422cb780.js"],
	"Service Worker": ["https:\/\/whatwebcando.today\/client\/index.422cb780.js"],
	"Shape Detection (Barcodes)": ["https:\/\/whatwebcando.today\/client\/index.422cb780.js"],
	"Shape Detection (Faces)": ["https:\/\/whatwebcando.today\/client\/index.422cb780.js"],
	"Shape Detection (Texts)": ["https:\/\/whatwebcando.today\/client\/index.422cb780.js"],
	"Storage Estimation": ["https:\/\/whatwebcando.today\/client\/index.422cb780.js"],
	"Web Share": ["https:\/\/whatwebcando.today\/client\/index.422cb780.js"],
	"Web Share (Files)": ["https:\/\/whatwebcando.today\/client\/index.422cb780.js"],
	"WebBluetooth": ["https:\/\/whatwebcando.today\/client\/index.422cb780.js"],
	"WebMIDI": ["https:\/\/whatwebcando.today\/client\/index.422cb780.js"],
	"WebNFC": ["https:\/\/whatwebcando.today\/client\/index.422cb780.js"],
	"WebOTP": ["https:\/\/whatwebcando.today\/client\/index.422cb780.js"],
	"WebSerial": ["https:\/\/whatwebcando.today\/client\/index.422cb780.js"],
	"WebUSB": ["https:\/\/whatwebcando.today\/client\/index.422cb780.js"]
}
```

**Pull request merged**
