### PR TITLE
Add Markup 2022 custom metrics

### LINKED ISSUE #17: Markup 2022 custom metrics
Progress on https://github.com/HTTPArchive/almanac.httparchive.org/issues/2881

- [x] Rendered node names of elements with the `shadowRoot` property
- [x] Pre-rendered mapping of `template` elements to `shadowroot` attribute values (null, empty, open, closed)
- [x] Number of `<slot>` elements per web component
- [x] `a[href]` values whose schemes are not considered [special](https://url.spec.whatwg.org/#special-scheme) (ftp, http, ws, etc)

cc @AlexLakatos

### PR DESCRIPTION
**Pull request by rviscomi**
Fixes #17 

Tests:

- [`anchors.hrefs_without_special_scheme`](https://webpagetest.httparchive.org/result/220523_4H_8/1/details/#waterfall_view_step1) (https://codepen.io/rviscomi/pen/YzerzNX)
- [Custom elements](https://webpagetest.httparchive.org/result/220523_1T_G/1/details/#waterfall_view_step1) (https://codepen.io/rviscomi/pen/MWQmdzq)
- [Custom elements](https://webpagetest.httparchive.org/result/220524_WE_5/1/details/#waterfall_view_step1) (https://dictionary.cambridge.org/plus/)

### CODE REVIEW

**Review by pmeenan — APPROVED** [review]
LGTM

**Comment by rviscomi** [comment]
More commits to come! I'll mark this "ready for review" when done.

**Comment by pmeenan** [comment]
Do you have WPT output from running against a few sites? Mostly curious about the output from a complex site to make sure the output doesn't baloon.

**Comment by rviscomi** [comment]
Yep, a few test links in the top comment. Here's a non-trivial site: https://webpagetest.httparchive.org/result/220524_WE_5/1/details/#waterfall_view_step1

**Comment by pmeenan** [comment]
THX, LGTM.

**Review by pmeenan — APPROVED** [review]

**Pull request merged**
